## HARSH ASHOK VALAMBE
## 20BRS1197
### LAB-2

In [ ]:
import numpy as np
x=np.array(12)
x

array(12)

In [ ]:
x.ndim

0

In [ ]:
x=np.array([12,3,6,14])
x

array([12,  3,  6, 14])

In [ ]:
x.ndim

1

In [ ]:
x=np.array([[12,3,6,14],[12,3,6,14]])
x

array([[12,  3,  6, 14],
       [12,  3,  6, 14]])

In [ ]:
x.ndim

2

In [ ]:
x=np.array([[[5,78,2,34,0], [6,79,3,35,1],
               [7,80,4,36,2]], [[5,78,2,34,0],
              [6,79,3,35,1], [7,80,4,36,2]],
              [[5,78,2,34,0], [6,79,3,35,1], [7,80,4,36,2]]])
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [ ]:
x.ndim

3

## Tensor Operations

In [ ]:

import keras
from keras import layers
from keras import models
from tensorflow.keras.activations import relu
from keras.layers import dot
keras.layers.Dense(512,activation='relu')
# output=relu(dot(W,input)+b)

def naive_relu(x):
  assert len(x.shape)==2
  x=x.copy()
  for i in range (x.shape[0]):
    for j in range (x.shape[1]):
      x[i,j]=max(x[i,j],0)
  return x


In [ ]:
def naive_add(x,y):
  assert len(x.shape)==2
  assert x.shape==y.shape
  x=x.copy()
  for i in range (x.shape[0]):
    for j in range (x.shape[1]):
      x[i,j]+=y[i,j]
  return x
  z=x+y
  z=np.maximum(z,0.)

In [ ]:
def naive_add_matrix_and_vector(x,y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[j]
  return x

import numpy as np 
x = np.random.random((64,3,32,10))
y = np.random.random((32,10))
z = np.maximum(x,y)

In [ ]:
import numpy as np

def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()

    for i in range(x.shape[0]):
      for j in range(x.shape[1]):
        x[i, j] = max(x[i,j], 0)    
    return x 

x = np.array([[-1,2,3,4],[8,7,-8,9]])
print(naive_relu(x))

[[0 2 3 4]
 [8 7 0 9]]


In [ ]:
# Import global tensorflow
import tensorflow as tf

In [ ]:
from tensorflow.keras import activations

x = np.array([[1,2,3,-4,-5],[6,7,-8,9,10]])
print(activations.relu(x))

tf.Tensor(
[[ 1  2  3  0  0]
 [ 6  7  0  9 10]], shape=(2, 5), dtype=int64)


In [ ]:
import numpy as np 

x = np.array([[1,2,3,4],[1,8,7,8]])
y = np.array([10,3,6,8])

print(x+y)

[[11  5  9 12]
 [11 11 13 16]]


In [ ]:
x = np.array([[1,2,3,4],[1,8,7,8]])
y = np.array([10,3,6,8])

print(naive_add_matrix_and_vector(x,y))

[[11  5  9 12]
 [11 11 13 16]]


## DECLARE 5-D TENSOR AND DISPLAY THE DIMENSION

In [ ]:
import numpy as np

x = np.array(
    [
        [
            [
                [
                    [1,2,3,4,5]
                ],
                [
                    [4,7,4,7,2]
                ],
                [
                    [3,2,1,0,5]
                ],            
            ],
            [
                [
                    [1,2,3,4,5]
                ],
                [
                    [3,2,1,0,5]
                ],
                [
                    [4,7,4,7,2]
                ],            
            ],
        ],
         [
            [
                [
                    [1,2,3,4,5]
                ],
                [
                    [3,2,1,0,5]
                ],
                [
                    [3,2,1,0,5]
                ],            
            ],
            [
                [
                    [1,2,3,4,5]
                ],
                [
                    [4,7,4,7,2]
                ],
                [
                    [4,5,1,3,5]
                ],            
            ],
        ],
          
    ]
)

print(x.shape)

(2, 2, 3, 1, 5)


## Take real time datasets for all 5 dimensions and perform basic tensor flow operations

In [ ]:
from google.colab import drive

drive.mount("/content/gdrive")

In [ ]:
import cv2
cap=cv2.VideoCapture('/content/sample1.mp4')
set1=[]
i=0
while(i<100):
  ret,frame=cap.read()
  if ret:
    frame=cv2.resize(frame,(300,300),fx=0,fy=0,
                     interpolation=cv2.INTER_CUBIC)
    set1.append(frame)
    i+=1
    if cv2.waitKey(25) & 0xFF==ord('q'):
      break
  else:
    cap.set(cv2.CAP_PROP_POS_FRAMES,0)
    break
cap.release()
cv2.destroyAllWindows()


In [ ]:
cap=cv2.VideoCapture('/content/sample1.mp4')
set2=[]
i=0
while(i<100):
  ret,frame=cap.read()
  if ret:
    frame=cv2.resize(frame,(300,300),fx=0,fy=0,
                     interpolation=cv2.INTER_CUBIC)
    set2.append(frame)
    i+=1
    if cv2.waitKey(25) & 0xFF==ord('q'):
      break
  else:
    cap.set(cv2.CAP_PROP_POS_FRAMES,0)
    break
cap.release()
cv2.destroyAllWindows()
vidset1=np.array([set1,set2])

In [ ]:
cap=cv2.VideoCapture('/content/sample3.mp4')
set1=[]
i=0
while(i<100):
  ret,frame=cap.read()
  if ret:
    frame=cv2.resize(frame,(300,300),fx=0,fy=0,
                     interpolation=cv2.INTER_CUBIC)
    set1.append(frame)
    i+=1
    if cv2.waitKey(25) & 0xFF==ord('q'):
      break
  else:
    cap.set(cv2.CAP_PROP_POS_FRAMES,0)
    break
cap.release()
cv2.destroyAllWindows()

In [ ]:
cap=cv2.VideoCapture('/content/sample4.mp4')
set2=[]
i=0
while(i<100):
  ret,frame=cap.read()
  if ret:
    frame=cv2.resize(frame,(300,300),fx=0,fy=0,
                     interpolation=cv2.INTER_CUBIC)
    set2.append(frame)
    i+=1
    if cv2.waitKey(25) & 0xFF==ord('q'):
      break
  else:
    cap.set(cv2.CAP_PROP_POS_FRAMES,0)
    break
cap.release()
cv2.destroyAllWindows()
vidset2=np.array([set1,set2])

In [ ]:
print(vidset1.shape)
print(vidset2.shape)

(2, 100, 300, 300, 3)
(2, 100, 300, 300, 3)


In [ ]:
def subvideo(x1,x2):
  assert x1.ndim==5
  assert x2.ndim==5
  for i1 in range(x1.shape[0]):
    for i2 in range(x1.shape[1]):
      for i3 in range(x1.shape[2]):
        for i4 in range(x1.shape[3]):
          for i5 in range(x1.shape[4]):
            if x1[i1][i2][i3][i4][i5]>x2[i1][i2][i3][i4][i5]:
              x1[i1][i2][i3][i4][i5]-=x2[i1][i2][i3][i4][i5]
            else:
              x2[i1][i2][i3][i4][i5]-=x1[i1][i2][i3][i4][i5]
              x1[i1][i2][i3][i4][i5]=x2[i1][i2][i3][i4][i5]

  return x1

In [ ]:
def addvideo(x1,x2):
  assert x1.ndim==5
  assert x2.ndim==5
  for i1 in range(x1.shape[0]):
    for i2 in range(x1.shape[1]):
      for i3 in range(x1.shape[2]):
        for i4 in range(x1.shape[3]):
          for i5 in range(x1.shape[4]):
            if x1[i1][i2][i3][i4][i5]+x2[i1][i2][i3][i4][i5]<255:
              x1[i1][i2][i3][i4][i5]+=x2[i1][i2][i3][i4][i5]
           


  return x1

In [ ]:
videoset1=subvideo(vidset1,vidset2)

In [ ]:
print(videoset1.shape)

(2, 100, 300, 300, 3)


In [ ]:
videoset2=addvideo(vidset1,vidset2)

<ipython-input-51-3f6a36e1594a>:9: RuntimeWarning: overflow encountered in ubyte_scalars
  if x1[i1][i2][i3][i4][i5]+x2[i1][i2][i3][i4][i5]<255:
<ipython-input-51-3f6a36e1594a>:10: RuntimeWarning: overflow encountered in ubyte_scalars
  x1[i1][i2][i3][i4][i5]+=x2[i1][i2][i3][i4][i5]


In [ ]:
print(videoset2.shape)

(2, 100, 300, 300, 3)


## IMPLEMENT A PERCEPTRON NETWORK FOR A SIMPLE ADDER CIRCUIT

In [ ]:
import numpy as np
  
def unitStep(x):
    if x>= 0:
        return 1
    else:
        return 0


In [ ]:
def perceptronModel(x, w, b):
    v = np.dot(w, x) + b
    y = unitStep(v)
    return y
  
def NOT_logicFunction(x):
    wn = -1
    bn = 0.5
    return perceptronModel(x, wn, bn)

In [ ]:
def AND_logicFunction(x):
    w = np.array([1, 1])
    b = -1.5
    return perceptronModel(x, w, b)

def NAND_logicFunction(x):
    o_AND = AND_logicFunction(x)
    o_NOT = NOT_logicFunction(o_AND)
    return o_NOT
  
def XOR_logicFunction(x):
  a_nand_b = NAND_logicFunction(x)
  part1 = NAND_logicFunction(np.array([x[0], a_nand_b]))
  part2 = NAND_logicFunction(np.array([x[1], a_nand_b]))

  return NAND_logicFunction(np.array([part1, part2]))

In [ ]:
test1 = np.array([0, 0])
test2 = np.array([0, 1])
test3 = np.array([1, 0])
test4 = np.array([1, 1])

# XOR
print(XOR_logicFunction(test1))
print(XOR_logicFunction(test2))
print(XOR_logicFunction(test3))
print(XOR_logicFunction(test4))

# AND
print(AND_logicFunction(test1))
print(AND_logicFunction(test2))
print(AND_logicFunction(test3))
print(AND_logicFunction(test4))

0
1
1
0
0
0
0
1
